### ISSUE TITLE
Introductory Text

### ISSUE THREAD

**Issue by danlopez** [CityOfPhiladelphia/property-data-explorer#222]
Update text in introduction sidebar

**Comment by phaedratinder** [comment]
Proposed text:

Welcome to the new Property Data Explorer for the City of Philadelphia

Search for one or more properties to 
•	Get information about property ownership, value, and physical characteristics
•	Look up the history of sales and assessments for a property
•	Quickly compare properties on a block or within a nearby area
•	Generate address listings near a property or within an area of interest
•	Find properties anywhere in the city owned by an individual or company

To get started, you can
•	Click anywhere on the map
•	Use   to search near a property or   to draw an area
•	Type an address, owner name, property account number, or Department of Records Map Registry number into the search box
