### ISSUE TITLE
fix app in IE

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#241]
Map window is unresponsive. If you give it an url with a search, the buttons and interaction will work in the table section below (but still not for the map portion above.)

Example address: 500 Regatta Dr

**Comment by ajrothwell** [comment]
this stopped working when I added an import of "leaflet-event-forwarder" to MapPanel.vue.  I added that so that you could highlight the parcels under the vector marker more easily
