### ISSUE TITLE
Split Zoning doesn't display any zoning

### ISSUE THREAD

**Issue by regisshogan** [CityOfPhiladelphia/property-data-explorer#28]
e.g.

1607-19 Catharine St

**Comment by stevetotheizz0** [comment]
Console.log of item shows that zoning is blank. Possibly related to condo or properties with "related" results. 

Wait until resolving condos to see if solution is related/similar.

**Comment by stevetotheizz0** [comment]
Fixed zoning for owner search. (Path was slightly different)

**Comment by stevetotheizz0** [comment]
For  1607-19 Catharine St, it looks like opa_properties_public has a blank zoning field, while the record from ais has the zoning code included.

Alex said that this is a known problem and they are trying to have opa use the ais data for this field in their data, which would resolve the issue.
