### ISSUE TITLE
when search returns more than 200 records, include those within the current map view first

### ISSUE THREAD

**Issue by phaedratinder** [CityOfPhiladelphia/property-data-explorer#305]
ex: search for "Smith" will return 4715 properties.  currently no way for user to control which 200 of those properties come back.  allowing the map extent to determine the order by which records are returned, allowing them to be visible in the results table, makes this feature more usable for people who have a general area in mind they are looking for.

currently bulk search results apply primarily to owner search, but future plans to add attribute search functionality would prioritize results in the same way

**Comment by danlopez** [comment]
Our plan for initial launch is as follows: 

Instead of restricting search to the current view (which is probably doable but is a big lift at the moment), we'd like to show the user a message stating that this isn't showing all of the results and we'd suggest a more specific search term.
