### ISSUE TITLE
CSV doesn't write all data

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#310]
Its likely a regression in which special characters such as "#" are causing an error.

https://property-beta.phila.gov/#/?shape=%5B%5B39.93642,-75.14906%5D,%5B39.93538,-75.14829%5D,%5B39.93573,-75.14603%5D,%5B39.93667,-75.14631%5D,%5B39.93701,-75.14816%5D%5D

**Comment by ajrothwell** [comment]
This is fixed in this commit of pvd: https://github.com/CityOfPhiladelphia/phila-vue-comps/tree/0bd1fb612b78190fd230a0467f03481e532b1aa5
