### ISSUE TITLE
Property not returning address or units

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#313]
See 116 Fernon St, , 1626 S Front St, or 1624 S Front St.

(I found these when adding new mapping for number of stories and this one field comes back unavailable from shapeSearches.  This method could find more examples if needed.)

Similar but different example:

https://property-beta.phila.gov/#/?shape=%5B%5B39.92536,-75.14994%5D,%5B39.92533,-75.14998%5D,%5B39.92529,-75.14992%5D%5D

**Comment by ajrothwell** [comment]
I do not see what is missing when I look at these addresses
