### ISSUE TITLE
Address Search doesnt Page more than 100 Condos

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#333]
If you search for a large condo using the mapclick or shapeSearch it will return the full number of units (ie.- 200) however if you type in the address it will not page past the first 100 and shows only the partial list of results.

**Comment by ajrothwell** [comment]
this was mostly fixed on 1/22, but more details in new PRs created 1/23 and 1/24 should be approved before this is closed
