### ISSUE TITLE
ShapeSearch outside of city limits does not return an error or let you clear the shape.

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#335]
Need to add a message of no records with the clear button for searches outside of the city.

**Comment by ajrothwell** [comment]
This is kind of like drawing a shape in the river or a shape that is completely in a street - it doesn't find any parcels, so it leaves the shape on the map.

It also doesn't clear the previous search, so I guess the screen at that point looks a little weird - you might have other parcels still highlighted, and a shape in the river that is unrelated.

I don't think any of it matters though.  I think it SHOULDN'T bother clearing a previous search if you draw a shape that surrounds nothing.  That's kind of clear from the shape being in the river or wherever the user put it.
