### ISSUE TITLE
Safari- Search for a property and navigate to the property details and close it the mailing lables and download buttons are misplaced 

### ISSUE THREAD

**Issue by AnushaErrabelli** [CityOfPhiladelphia/property-data-explorer#337]
To recreate: 

Catalina 10.15 
Safari 13.0

Search on 1234 mkt then open and close property card.

![Screen Shot 2020-01-14 at 2 11 55 PM](https://user-images.githubusercontent.com/37459695/72374271-eec55600-36d7-11ea-996d-d52059cd4ec7.png)

**Comment by ajrothwell** [comment]
I am not seeing this one

**Comment by ajrothwell** [comment]
oh wait, yes I do

**Comment by ajrothwell** [comment]
fixed
