### ISSUE TITLE
ShapeSearch works inconsistently on mobile

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#338]
The searches often add a marker (like from a geocode) and sometimes only search for the one property where the marker was located. 

It will say "showing 41 results" with only the one geocoded

**Comment by ajrothwell** [comment]
This is something I spent a week on and went crazy and gave up on a few months ago

**Comment by ajrothwell** [comment]
I think we just said, "oh well, internet explorer users are gonna have to live with this" and gave up
