### ISSUE TITLE
Testing Scenarios to Cover

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#394]
Search patterns: 

Each combination coming from and going to: shape, buffer, owner, address.
Including condos as well to make sure the correct number are loading and the button works.

Common issues:

CSV download not working or exporting all the records
Property card not loading or rendering everything.
Table not showing results, or the correct number of results.
Cyclomedia

Consistent Results:

Each shape type on the same property should give the same number of results and info. 

Routing:

Does routing update properly and does using nav cause the app to load the new search and render everything correctly.

Common addresses to use that are good for highlighting potential issues:

Condo example: 1100 vine st (203 units)
More?

Mobile testing: does everything work? cyclomedia, card etc

To gather all the issues we've had in the past I searched through this list:
https://github.com/CityOfPhiladelphia/property-data-explorer/issues?q=is%3Aissue+is%3Aclosed

**Comment by AnushaErrabelli** [comment]
Test scenarios for search: 
1. Address + Buffer search
2. shape + Buffer
3. OPA
4. Grantee (owner)
5. Address + Shape
6. Name +Shape
7. Condo address
8. Problem Address
9.  Name + Address ?
