### ISSUE TITLE
New Button Style Questions

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#408]
What do do with cancel / finish buttons?
Mobile style?

**Comment by sarahall** [comment]
@stevetotheizz0 **Mobile btns** - change color to match desktop

**For tooltips**: see image below for placement 
Tooltip text:
**Search** Type an address, owner name, property account number, or Department of Records registry map number.
**Draw boundaries** Draw a shape on the map.
**Select Radius** Select a point on the map to show all parcels within 250-foot radius.
  
![✅ action button variations - active](https://user-images.githubusercontent.com/10891276/79591449-873bef80-80a6-11ea-88ad-18027a48af93.png)
